[package]
name = "labrador"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rand = {version = "0.9", default-features = false, features = ["thread_rng", "unbiased"] }
thiserror = {version = "1.0", default-features = false }



[features]
skip-slow-tests = []

